# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-terminal.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-terminal.spec
    - .packit.yaml

upstream_package_name: deepin-terminal
# downstream (Fedora) RPM package name
downstream_package_name: deepin-terminal

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"0,/Version:/ s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-terminal.spec"
